version: "3.9"
services:
  php:
    build:
      ./php
    volumes:
      - ../src/:/var/www
  nginx:
    depends_on:
      - php
    build:
      ./nginx
    volumes:
      - ../src/:/var/www
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf/sites-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./nginx/conf/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/conf/conf/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf/conf/mime.types:/etc/nginx/mime.types
      - ./nginx/conf/conf/upstream.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/error.log:/var/logs/error.log
      - ./nginx/logs/access.log:/etc/nginx/logs/access.log
      - ./nginx/logs/access.log:/var/www/logs/access.log
    ports:
      - 81:80
      - 443:443
  nodejs:
    build:
      context: ./nodejs/
    volumes:
      - ../src/:/app/
    depends_on:
      - nginx
    ports:
      - "3000:3000"
