version: "3.9"
services:
  php:
    build:
      ./php
    volumes:
      - ../src/:/var/www
  nginx:
    depends_on:
      - php
    build:
      ./nginx
    volumes:
      - ../src/:/var/www
    ports:
      - 81:80
      - 443:443
  nodejs:
    build:
      context: ./nodejs/
    volumes:
      - ../src/:/app/
    depends_on:
      - nginx
    ports:
      - "3000:3000"
